//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApp1.Properties {
    using System;
    
    
    /// <summary>
    ///   Yerelleştirilmiş dizeleri aramak gibi işlemler için, türü kesin olarak belirtilmiş kaynak sınıfı.
    /// </summary>
    // Bu sınıf ResGen veya Visual Studio gibi bir araç kullanılarak StronglyTypedResourceBuilder
    // sınıfı tarafından otomatik olarak oluşturuldu.
    // Üye eklemek veya kaldırmak için .ResX dosyanızı düzenleyin ve sonra da ResGen
    // komutunu /str seçeneğiyle yeniden çalıştırın veya VS projenizi yeniden oluşturun.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Bu sınıf tarafından kullanılan, önbelleğe alınmış ResourceManager örneğini döndürür.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsFormsApp1.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Tümü için geçerli iş parçacığının CurrentUICulture özelliğini geçersiz kular
        ///   CurrentUICulture özelliğini tüm kaynak aramaları için geçersiz kılar.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap _404d0eff_b0f3_4853_944f_19bef6dbf780 {
            get {
                object obj = ResourceManager.GetObject("_404d0eff-b0f3-4853-944f-19bef6dbf780", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage AllApps {
            get {
                object obj = ResourceManager.GetObject("AllApps", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Bank {
            get {
                object obj = ResourceManager.GetObject("Bank", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Bank1 {
            get {
                object obj = ResourceManager.GetObject("Bank1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Bank2 {
            get {
                object obj = ResourceManager.GetObject("Bank2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap Black_White_Minimal_Business_Instagram_Reel_Cover__1_ {
            get {
                object obj = ResourceManager.GetObject("Black White Minimal Business Instagram Reel Cover (1)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage bo_project {
            get {
                object obj = ResourceManager.GetObject("bo_project", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Cancel {
            get {
                object obj = ResourceManager.GetObject("Cancel", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Cancel1 {
            get {
                object obj = ResourceManager.GetObject("Cancel1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Cancel2 {
            get {
                object obj = ResourceManager.GetObject("Cancel2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Cancel3 {
            get {
                object obj = ResourceManager.GetObject("Cancel3", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage chartdatalabels_insideend {
            get {
                object obj = ResourceManager.GetObject("chartdatalabels_insideend", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage CheckboxIndeterminate {
            get {
                object obj = ResourceManager.GetObject("CheckboxIndeterminate", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeMaximize {
            get {
                object obj = ResourceManager.GetObject("ChromeMaximize", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeMinimize {
            get {
                object obj = ResourceManager.GetObject("ChromeMinimize", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeMinimize1 {
            get {
                object obj = ResourceManager.GetObject("ChromeMinimize1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeMinimizeContrast {
            get {
                object obj = ResourceManager.GetObject("ChromeMinimizeContrast", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeRestore {
            get {
                object obj = ResourceManager.GetObject("ChromeRestore", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeRestore1 {
            get {
                object obj = ResourceManager.GetObject("ChromeRestore1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ChromeRestore2 {
            get {
                object obj = ResourceManager.GetObject("ChromeRestore2", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Document {
            get {
                object obj = ResourceManager.GetObject("Document", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage DownloadMap {
            get {
                object obj = ResourceManager.GetObject("DownloadMap", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage DuplexLandscapeOneSided {
            get {
                object obj = ResourceManager.GetObject("DuplexLandscapeOneSided", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage EndPointSolid {
            get {
                object obj = ResourceManager.GetObject("EndPointSolid", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap ezgif_5_5a26cbf02f {
            get {
                object obj = ResourceManager.GetObject("ezgif-5-5a26cbf02f", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap financial_32x32 {
            get {
                object obj = ResourceManager.GetObject("financial_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage GuestUser {
            get {
                object obj = ResourceManager.GetObject("GuestUser", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap icons8_delete {
            get {
                object obj = ResourceManager.GetObject("icons8_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap images_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("images-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap indir_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("indir-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap indir_removebg_preview1 {
            get {
                object obj = ResourceManager.GetObject("indir-removebg-preview1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap istockphoto_1070095458_612x612_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("istockphoto-1070095458-612x612-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Market {
            get {
                object obj = ResourceManager.GetObject("Market", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage OtherUser {
            get {
                object obj = ResourceManager.GetObject("OtherUser", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage People {
            get {
                object obj = ResourceManager.GetObject("People", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage People1 {
            get {
                object obj = ResourceManager.GetObject("People1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_nevtug_491138436_16527967 {
            get {
                object obj = ResourceManager.GetObject("pexels-nevtug-491138436-16527967", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap pexels_nevtug_491138436_165279671 {
            get {
                object obj = ResourceManager.GetObject("pexels-nevtug-491138436-165279671", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_dollar_sign_dollar_sign_money_icon_green_dollar_symbol_background_text_logo_sign_thumbnail {
            get {
                object obj = ResourceManager.GetObject("png-transparent-dollar-sign-dollar-sign-money-icon-green-dollar-symbol-background" +
                        "-text-logo-sign-thumbnail", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   System.Drawing.Bitmap türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static System.Drawing.Bitmap png_transparent_dollar_sign_dollar_sign_money_icon_green_dollar_symbol_background_text_logo_sign_thumbnail_removebg_preview {
            get {
                object obj = ResourceManager.GetObject("png-transparent-dollar-sign-dollar-sign-money-icon-green-dollar-symbol-background" +
                        "-text-logo-sign-thumbnail-removebg-preview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage portrait {
            get {
                object obj = ResourceManager.GetObject("portrait", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage PrintAllPages {
            get {
                object obj = ResourceManager.GetObject("PrintAllPages", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ProgressRingDots {
            get {
                object obj = ResourceManager.GetObject("ProgressRingDots", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage QRCode {
            get {
                object obj = ResourceManager.GetObject("QRCode", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ReceiptPrinter {
            get {
                object obj = ResourceManager.GetObject("ReceiptPrinter", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Refresh {
            get {
                object obj = ResourceManager.GetObject("Refresh", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Refresh1 {
            get {
                object obj = ResourceManager.GetObject("Refresh1", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ReportDocument {
            get {
                object obj = ResourceManager.GetObject("ReportDocument", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage ResizeMouseWide {
            get {
                object obj = ResourceManager.GetObject("ResizeMouseWide", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Setting {
            get {
                object obj = ResourceManager.GetObject("Setting", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage sparklinebar {
            get {
                object obj = ResourceManager.GetObject("sparklinebar", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage StorageTape {
            get {
                object obj = ResourceManager.GetObject("StorageTape", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage SwitchUser {
            get {
                object obj = ResourceManager.GetObject("SwitchUser", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
        
        /// <summary>
        ///   DevExpress.Utils.Svg.SvgImage türünde yerelleştirilmiş bir kaynak arar.
        /// </summary>
        internal static DevExpress.Utils.Svg.SvgImage Trackers {
            get {
                object obj = ResourceManager.GetObject("Trackers", resourceCulture);
                return ((DevExpress.Utils.Svg.SvgImage)(obj));
            }
        }
    }
}
